name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
  compile_and_run:
    runs-on: ubuntu-latest
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 
        run: git submodule update --init
      - name: 
        run: cmake -S . -B build
      - name:
        run: cmake --build build -j
      - name: Run
        run: ./build/address_book




jobs:
  compile_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile C program
        run: gcc test.c -o test

      - name: Run compiled program
        run: ./test